version: "3.7"
services:
  worker:
    image: grid_search_cpp_worker
    depends_on:
      - manager
    deploy:
      replicas: 3
      restart_policy:
        condition: none
    # TODO: remove tty and stdin_open
    stdin_open: true
    tty: true
    environment:
      - NODE_ID=worker_{{.Task.Slot}}

  manager:
    image: grid_search_cpp_manager
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    # TODO: remove tty and stdin_open
    stdin_open: true
    tty: true