version: "3.7"
services:
  worker:
    image: grid_search_cpp_worker
    depends_on:
      - manager
    deploy:
      replicas: 3
      restart_policy:
        condition: none
    #TODO: remove tty and stdin_open
    stdin_open: true
    tty: true

  manager:
    image: grid_search_cpp_manager
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    #TODO: remove tty and stdin_open
    stdin_open: true
    tty: true