version: "3.7"
services:
  worker:
    image: grid_search_cpp_worker
    # build:
    #   context: ./src/
    #   dockerfile: worker/Dockerfile
    entrypoint: ./app/worker/cmake-build-debug/master-gs
    depends_on:
      - manager
    deploy:
      replicas: 2 # This number should be equal to N_WORKERS
      restart_policy:
        condition: none
    # TODO: remove tty and stdin_open
    stdin_open: true
    tty: true
    environment:
      - NODE_ID=worker_{{.Task.Slot}}

  manager:
    image: grid_search_cpp_manager
    # build:
    #   context: ./src/
    #   dockerfile: master/Dockerfile
    entrypoint: ./app/master/cmake-build-debug/worker-gs
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    # TODO: remove tty and stdin_open
    stdin_open: true
    tty: true
    environment:
      - N_WORKERS=2 # This number should be equal to "replicas" in worker service