version: "3.7"

services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    volumes:
      - "./statsd.config.js:/opt/statsd/config.js:ro"
      - "./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro"
      - "./graphite:/opt/graphite/storage/:rw"
    ports:
      - "8080:8080"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    command: >
      -storage_driver="statsd"
      -storage_driver_host="graphite:8125"
      -storage_driver_db="cadvisor"
      -storage_driver_buffer_duration="10s"
      --enable_metrics=cpu,cpuLoad,disk,diskIO,memory,network
    depends_on:
      - graphite
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8081:3000"
    volumes:
      - "grafana_config:/var/lib/grafana"
    depends_on:
      - graphite

  worker:
    build:
      context: ./src/
      dockerfile: worker/Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - graphite
      - manager
    deploy:
      replicas: 4 # This number should be equal to N_WORKERS
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=worker_{{.Task.Slot}}

  manager:
    build:
      context: ./src/
      dockerfile: master/Dockerfile
    depends_on:
      - graphite
    deploy:
      restart_policy:
        condition: none
    tty: true
    stdin_open: true
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=manager
      - N_WORKERS=4 # This number should be equal to "replicas" in worker service

volumes:
  grafana_config:
    driver: local