version: "3.7"
services:
  worker:
    build:
      context: ./src/
      dockerfile: worker/Dockerfile
    depends_on:
      - manager
    deploy:
      replicas: 2 # This number should be equal to N_WORKERS
      restart_policy:
        condition: none
    # TODO: remove tty and stdin_open
    stdin_open: true
    tty: true
    environment:
      - NODE_ID=worker_{{.Task.Slot}}

  manager:
    build:
      context: ./src/
      dockerfile: master/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    # TODO: remove tty and stdin_open
    stdin_open: true
    tty: true
    environment:
      - N_WORKERS=2 # This number should be equal to "replicas" in worker service